#!/usr/bin/env php
<?php

require_once __DIR__ . '/vendor/autoload.php';


// Create the Application
$application = new \Symfony\Component\Console\Application;

// Register all Commands
$application->add(new \App\Console\SeedCommand);

// Run it
$application->run();