#!/usr/bin/env php
<?php

namespace App\Console;
require getcwd() . '/vendor/autoload.php';



// Create the Application
$application = new \Symfony\Component\Console\Application;

// Register all Commands
$application->add(new SeedCommand);

// Run it
$application->run();